#!/usr/bin/env bash
# Extract tutorial steps from test output
# Usage: ./docs/extract-tutorial.sh > docs/tutorial-output.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_FILE="$SCRIPT_DIR/../tests/test-31-tutorial-evolution.sh"

echo "# Patchstack Tutorial: Live Output"
echo ""
echo "This document shows the actual output from running the patchstack tutorial test."
echo "It is automatically generated to stay in sync with the test."
echo ""
echo '```bash'
echo "$ ./tests/test-31-tutorial-evolution.sh"
echo '```'
echo ""
echo '```'

# Run the test and capture output
bash "$TEST_FILE" 2>&1

echo '```'
echo ""
echo "---"
echo ""
echo "*This output is generated by running \`./docs/extract-tutorial.sh > docs/TUTORIAL.md\`*"
